[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
board_build.partitions = default_8MB.csv
monitor_speed = 115200
build_flags =
	-std=c++17
	-DCORE_DEBUG_LEVEL=0
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	m5stack/M5Cardputer @ 1.1.1
	earlephilhower/ESP8266Audio@2.2.0
