#pragma once
#include "State.h"
void drawSplash(const char *statusLine);
void drawAll();
void drawHeader();
void drawTrackList();
void drawStatus();
void toggleHelp();
void drawHelp();
void drawRadioAll();
void drawRadioHeader();
void drawRadioRow(int idx);
void drawRadioList();
void drawRadioStatus();
void drawOverlayFrame(const char *title);
void drawWifiOverlay();
void drawWifiPassOverlay(bool inputOnly = false);
void drawAddUrlOverlay(bool inputOnly = false);
void drawAddNameOverlay(bool inputOnly = false);
void drawRemoveConfirm();
void showHdrMsg(const char *msg);
void showToast();
void cycleRepeat();
void toggleShuffle();
void setTheme(uint8_t idx);
void toggleScreen();
void wakeScreen();
void enterSettingsMenu();
void exitSettingsMenu();
void drawSettingsMenu();
void handleSettingsInput(Keyboard_Class::KeysState &ks);
void toggleDebug();
void enterEQScreen();
void exitEQScreen();
void drawEQScreen();
void handleEQInput(Keyboard_Class::KeysState &ks);
void drawDebug();